<?php

$labels['notes'] = 'Jegyzetek';
$labels['title'] = 'Cím';
$labels['body'] = 'Jegyzet';
$labels['newnote'] = 'Új jegyzet';
$labels['save'] = 'Mentés';
$labels['delete'] = 'Törlés';
$labels['saved'] = 'Jegyzet elmentve.';
$labels['savedcopy'] = 'Jegyzet másolatként mentve.';
$labels['deleted'] = 'Jegyzet törölve.';
$labels['untitlednote'] = 'Cím nélküli jegyzet';
$labels['conflicttitle'] = 'Ütközés áll fenn';
$labels['conflictmessage'] = 'Létezik egy újabb távoli verzió. Töltse újra, írja felül vagy előzetes mentés másolatként.';
$labels['savemycopy'] = 'Elmentés másolatként';
$labels['reloadremote'] = 'Távoli verzió betöltése';
$labels['overwrite'] = 'Felülírás az ittenivel';
$labels['retrycleanup'] = 'Ismételt törlési kísérlet';
$labels['renderedpreview'] = 'Előnézet kiszámolása';
$labels['revisioncleanuppending'] = 'A legújabb jegyzet verzió érhető el, de a régi törlése még mindig folyamatban.';
$labels['cleanuppendinglabel'] = 'Törlés függőben.';
$labels['cleanuppending'] = 'Elhalasztott törlés még mindig folyamatban.';
$labels['deletecleanuppending'] = 'A jegyzet rejtett volt, a végső törlés még mindig folyamatban.';
$labels['cleanupdone'] = 'Megakadt törlés sikerült.';
$labels['reloaded'] = 'A távoli verzió újbóli betöltése.';
$labels['deleteconfirm'] = 'Törli ezt a jegyzetet?';
$labels['foldererror'] = 'A "%s" jegyzet mailbox elérése vagy létrehozása sikertelen.';
